function [seqs, attrNames, attrAnnotation] = TB100_Subsets_Attributes()

attrSpec = TB100_AttrSpec;
numAttr = length(attrSpec);

seqs = {};
attrNames = {};
count = 1;
for i = 1 : numAttr
   s = strtrim(lower(strsplit(attrSpec{i}.SEQUENCES, ',')));
   attrNames{end+1} = attrSpec{i}.NAME;
   for j = 1 : length(s)
      if isempty(seqs) || ~any(strcmp(s{j}, seqs))
         seqs{count} = lower(s{j}); 
         count = count + 1;
      end
   end
end
numSeq = length(seqs);

attrAnnotation = zeros(numSeq, numAttr);
for i = 1 : numAttr
    s = strtrim(lower(strsplit(attrSpec{i}.SEQUENCES, ',')));
    for j = 1 : length(s)
        idx = find(strcmp(s{j}, seqs));
        attrAnnotation(idx, i) = 1;
    end
end



function attrSpec = TB100_AttrSpec
% created w.r.t. the specification, http://cvlab.hanyang.ac.kr/tracker_benchmark/datasets.html

attrSpec = {struct('NAME', 'IV(IlluminationVariation)', ...
    'DESCRIPTION', 'the illumination in the target region is significantly changed.', ...
    'SEQUENCES', ['Basketball, Box, Car1, Car2, Car24, Car4, CarDark, Coke, '...
    'Crowds, David, Doll, FaceOcc2, Fish, Human2, Human4.2, Human7, '...
    'Human8, Human9, Ironman, KiteSurf, Lemming, Liquor, Man, Matrix, '...
    'Mhyang, MotorRolling, Shaking, Singer1, Singer2, Skating1, Skiing, '...
    'Soccer, Sylvester, Tiger1, Tiger2, Trans, Trellis, Woman']), ...
    struct('NAME', 'SV(ScaleVariation)', ...
    'DESCRIPTION', ['the ratio of the bounding boxes of the first frame and '...
    'the current frame is out of the range ts, ts > 1 (ts=2).'],...
    'SEQUENCES', ['Biker, BlurBody, BlurCar2, BlurOwl, Board, Box, Boy, Car1, '...
    'Car24, Car4, CarScale, ClifBar, Couple, Crossing, Dancer, David, '...
    'Diving, Dog, Dog1, Doll, DragonBaby, Dudek, FleetFace, Freeman1, '...
    'Freeman3, Freeman4, Girl, Girl2, Gym, Human2, Human3, Human4.2, '...
    'Human5, Human6, Human7, Human8, Human9, Ironman, Jump, Lemming, '...
    'Liquor, Matrix, MotorRolling, Panda, RedTeam, Rubik, Shaking, Singer1, '...
    'Skater, Skater2, Skating1, Skating2.1, Skating2.2, Skiing, Soccer, '...
    'Surfer, Toy, Trans, Trellis, Twinnings, Vase, Walking, Walking2, Woman']), ...
    struct('NAME', 'OCC(Occlusion)',...
    'DESCRIPTION', 'the target is partially or fully occluded.',...
    'SEQUENCES', ['Basketball, Biker, Bird2, Bolt, Box, CarScale, ClifBar, '...
    'Coke, Coupon, David, David3, Doll, DragonBaby, Dudek, FaceOcc1, '...
    'FaceOcc2, Football, Freeman4, Girl, Girl2, Human3, Human4.2, '...
    'Human5, Human6, Human7, Ironman, Jogging.1, Jogging.2, Jump, KiteSurf, '...
    'Lemming, Liquor, Matrix, Panda, RedTeam, Rubik, Singer1, Skating1, '...
    'Skating2.1, Skating2.2, Soccer, Subway, Suv, Tiger1, Tiger2, Trans, '...
    'Walking, Walking2, Woman']), ...
    struct('NAME', 'DEF(Deformation)',...
    'DESCRIPTION', 'non-rigid object deformation.',...
    'SEQUENCES', ['Basketball, Bird1, Bird2, BlurBody, Bolt, Bolt2, Couple, '...
    'Crossing, Crowds, Dancer, Dancer2, David, David3, Diving, Dog, '...
    'Dudek, FleetFace, Girl2, Gym, Human3, Human4.2, Human5, Human6, '...
    'Human7, Human8, Human9, Jogging.1, Jogging.2, Jump, Mhyang, Panda, '...
    'Singer2, Skater, Skater2, Skating1, Skating2.1, Skating2.2, Skiing, '...
    'Subway, Tiger1, Tiger2, Trans, Walking, Woman']), ...
    struct('NAME', 'MB(MotionBlur)',...
    'DESECRIPTION', ['the target region is blurred '...
    'due to the motion of target or camera.'],...
    'SEQUENCES', ['Biker, BlurBody, BlurCar1, BlurCar2, BlurCar3, BlurCar4, '...
    'BlurFace, BlurOwl, Board, Box, Boy, ClifBar, David, Deer, '...
    'DragonBaby, FleetFace, Girl2, Human2, Human7, Human9, Ironman, '...
    'Jump, Jumping, Liquor, MotorRolling, Soccer, Tiger1, Tiger2, Woman']), ...
    struct('NAME', 'FM(FastMotion)',...
    'DESCRIPTION', ['the motion of the ground truth is '...
    'larger than tm pixels (tm=20).'],...
    'SEQUENCES', ['Biker, Bird1, Bird2, BlurBody, BlurCar1, BlurCar2, '...
    'BlurCar3, BlurCar4, BlurFace, BlurOwl, Board, Boy, CarScale, ClifBar, '...
    'Coke, Couple, Deer, DragonBaby, Dudek, FleetFace, Human6, Human7, '...
    'Human9, Ironman, Jumping, Lemming, Liquor, Matrix, MotorRolling, '...
    'Skater2, Skating2.1, Skating2.2, Soccer, Surfer, Tiger1, Tiger2, '...
    'Toy, Vase, Woman']), ...
    struct('NAME', 'IPR(In-PlaneRotation)',...
    'DESCRIPTION', 'the target rotates in the image plane.',...
    'SEQUENCES', ['Bird2, BlurBody, BlurFace, BlurOwl, Bolt, Box, Boy, '...
    'CarScale, ClifBar, Coke, Dancer, David, David2, Deer, Diving, '...
    'Dog1, Doll, DragonBaby, Dudek, FaceOcc2, FleetFace, Football, '...
    'Football1, Freeman1, Freeman3, Freeman4, Girl, Gym, Ironman, '...
    'Jump, KiteSurf, Matrix, MotorRolling, MountainBike, Panda, '...
    'RedTeam, Rubik, Shaking, Singer2, Skater, Skater2, Skiing, Soccer, '...
    'Surfer, Suv, Sylvester, Tiger1, Tiger2, Toy, Trellis, Vase']), ...
    struct('NAME', 'OPR(Out-of-PlaneRotatio)',...
    'DESCRIPTION', 'the target rotates out of the image plane.',...
    'SEQUENCES', ['Basketball, Biker, Bird2, Board, Bolt, Box, Boy, '...
    'CarScale, Coke, Couple, Dancer, David, David2, David3, Dog, Dog1, '...
    'Doll, DragonBaby, Dudek, FaceOcc2, FleetFace, Football, Football1, '...
    'Freeman1, Freeman3, Freeman4, Girl, Girl2, Gym, Human2, Human3, '...
    'Human6, Ironman, Jogging.1, Jogging.2, Jump, KiteSurf, Lemming, '...
    'Liquor, Matrix, Mhyang, MountainBike, Panda, RedTeam, Rubik, '...
    'Shaking, Singer1, Singer2, Skater, Skater2, Skating1, Skating2.1, '...
    'Skating2.2, Skiing, Soccer, Surfer, Sylvester, Tiger1, Tiger2, '...
    'Toy, Trellis, Twinnings, Woman']), ...
    struct('NAME', 'OV(Out-of-View)',...
    'DESCRIPTION', 'some portion of the target leaves the view.',...
    'SEQUENCES', ['Biker, Bird1, Board, Box, ClifBar, DragonBaby, Dudek, '...
    'Human6, Ironman, Lemming, Liquor, Panda, Suv, Tiger2']), ...
    struct('NAME', 'BC(BackgroundClutters)',...
    'DESCRIPTION', ['the background near the target '...
    'has the similar color or texture as the target.'],...
    'SEQUENCES', ['Basketball, Board, Bolt2, Box, Car1, Car2, Car24, '...
    'CarDark, ClifBar, Couple, Coupon, Crossing, Crowds, David3, '...
    'Deer, Dudek, Football, Football1, Human3, Ironman, Liquor, '...
    'Matrix, Mhyang, MotorRolling, MountainBike, Shaking, Singer2, '...
    'Skating1, Soccer, Subway, Trellis']),...
    struct('NAME', 'LR(LowResolution)',...
    'DESCRIPTION', ['the number of pixels inside the '...
    'ground-truth bounding box is less than tr (tr =400).'],...
    'SEQUENCES', 'Biker, Car1, Freeman3, Freeman4, Panda, RedTeam, Skiing, Surfer, Walking')...
    };